obj = {"regno":1,'fname':"rajni",'lname':"kant","contno":6370142412,"math":91,"phy":81,"chem":45,'gender':"male"}
obj.setdefault("Dept")
print(obj)
print(obj.values())
print(obj.items())
print(obj.get(1))
print(obj.get(55, "Not Found"))
obj.update({81: "Bio"})
print(obj)
obj.setdefault(1, "Rollno")
print(obj)
obj.pop(1)
print(obj)
obj.popitem()
print(obj)
newobj = obj.copy()
print(newobj)
newobj.clear()
print(newobj)
